before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

#rspec:
#script:
    #- bundler exec rspec

deploy:
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  stage: deploy
  script: tar -cJf - ./ | ssh -v sb@api.sb.im 'mkdir -p ncp && cd ncp && tar -xJf -'
  only:
    refs:
      - master

deploy:
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SIMULATION_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  stage: deploy
  script:
    - go version
    - GOOS=linux GOARCH=arm go build
    - tar -cJf - ./ | ssh pi@api.sb.im -p 6002 'mkdir -p ncp && cd ncp && tar -xJf -'
  only:
    refs:
      - dev

