nfpms:
  - id: package
    package_name: ncp
    file_name_template: "{{ .ConventionalFileName }}"
    builds:
      - ncp
    vendor: SB.IM Inno
    homepage: https://github.com/sb-im/ncp
    maintainer: a-wing <1@233.email>
    description: |-
      Edge gateway core communication service
    license: MPL 2.0
    formats:
      - apk
      - deb
      - archlinux
    bindir: /usr/bin
    epoch: 2
    version_metadata: git
    release: 1
    section: sbim
    priority: extra
    contents:
      - src: conf/config-dist.yml
        dst: /etc/ncp/
      - src: conf/ncp.service
        dst: /lib/systemd/system/
      - src: conf/ncp@.service
        dst: /lib/systemd/system/
    deb:
      lintian_overrides:
        - statically-linked-binary

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X "sb.im/ncp/constant.Version={{.Version}}"
      - -X "sb.im/ncp/constant.Commit={{.Commit}}"
      - -X "sb.im/ncp/constant.BuildTime={{.Date}}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge'
      - '^build'
      - '^chore'
      - '^docs'
      - '^test'
      - '^ci'

