api_host: "localhost:3000"
id: 1

#mqtt: "mqtt[s]://[username][:password]@host.domain[:port]"
mqtt: "mqtt://admin:public@localhost:1883"

ctl:
  host: "localhost"
  port: 3300


# production, development
#env: "production"
env: "development"

# :debug < :info < :warn < :error < :fatal < :unknown
log_level: "info"

ncp:
  download:
    map: '../map'
  status:
    - link_id: 2
    - position_ok: true
    - lat: "22.0000100001"
    - lng: "144.0000100001"
    - alt: "10088.0001"

