server:
  id: 1
  secret_key: ""
  #mqtt: "mqtt[s]://[username][:password]@host.domain[:port]"
  mqtt: "mqtt://admin:public@localhost:1883"
  #mqtt: "mqtt://admin:public@mqtt.sblab.xyz:1883"
  tcpc: "localhost:8980"
  tcps: "localhost:1208"

# production, development
#env: "production"
env: "development"

# :debug < :info < :warn < :error < :fatal < :unknown
log_level: "info"

ncp:
  download:
    map: '../map'
  upload:
    map: '../map'
    air_log: 'log.log'
  status:
    link_id: 2
    position_ok: true
    lat: "22.0000100001"
    lng: "144.0000100001"
    alt: "10088.0001"
#  shell:
#    path: "scripts/"
#    prefix: "sh "
#    suffix: ".sh"


