server:
  id: 1
  secret_key: ""
  #mqtt: "mqtt[s]://[username][:password]@host.domain[:port]"
  mqtt: "mqtt://admin:public@localhost:1883"
  #mqtt: "mqtt://admin:public@mqtt.sblab.xyz:1883"
  tcpc: "localhost:8980"
  tcps: "localhost:1208"
  tran: "localhost:1122"

# production, development
#env: "production"
env: "development"

# :debug < :info < :warn < :error < :fatal < :unknown
log_level: "info"

ncp:
  webrtc:
    iceserver:
    - urls:
      - "stun:api.sb.im"
#      - "stun:stun.l.google.com:19302"
#    - urls:
#      - "turn:turnserver.example.org"
#      username: "webrtc"
#      credential: "turnpassword"
#      credentialType: 0
    # test video src
    driver: "gst"
    args: "videotestsrc ! videoconvert ! queue"
    # gst-launch-1.0 videotestsrc ! 'video/x-raw, width=640, height=480' ! videoconvert ! x264enc ! rtph264pay ! udpsink host=127.0.0.1 port=5004
    #args: 'udpsrc port=5004 caps="application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264" ! rtph264depay ! avdec_h264 ! videoconvert ! queue'
  download:
    map: '../map'
  upload:
    map: '../map'
    air_log: 'log.log'
  status:
    link_id: 2
    position_ok: true
    lat: "22.0000100001"
    lng: "144.0000100001"
    alt: "10088.0001"
#  shell:
#    path: "scripts/"
#    prefix: "sh"
#    suffix: ".sh"


