server:
  id: 1
  secret_key: ""
  #mqtt: "mqtt[s]://[username][:password]@host.domain[:port]"
  mqtt: "mqtt://admin:public@localhost:1883"
  #mqtt: "mqtt://admin:public@mqtt.sblab.xyz:1883"
  tcpc: "localhost:8980"
  tcps: "localhost:1208"
  tran: "localhost:1122"

mqttd:
  id: 1
  static:
    link_id: 1
    lat: "22.6876423001"
    lng: "114.2248673001"
    alt: "10088.0001"
  client: "node-%d"
  delay:   "nodes/%d/delay"
  status:  "nodes/%d/status"
  network: "nodes/%d/network"
  #broker: "mqtt://admin:public@mqtt.sblab.xyz:1883"
  broker: "mqtt://admin:public@localhost:1883"
  rpc :
    i: "nodes/%d/rpc/recv"
    o: "nodes/%d/rpc/send"
  gtran:
    prefix: "nodes/%d/msg/%s"
  trans:
    wether:
      retain: true
      qos: 0
    battery:
      retain: true
      qos: 0


ncpio:
  # tcps / tcpc / mqtt / history / logger / jsonrpc2 / build-in / api
  - type: api
    i_rules:
      - regexp: '.*'
        invert: true
    o_rules:
      - regexp: '.*'
        invert: true
  - type: jsonrpc2
    params: "233"
    i_rules:
      - regexp: '.*'
        invert: true
    o_rules:
      - regexp: '.*'
        invert: true
  - type: tcps
    params: "localhost:1222"
    i_rules:
      - regexp: '.*"method".*'
    o_rules:
      - regexp: '.*'
  - type: mqtt
    params: "config.yml"
    i_rules:
      - regexp: '.*'
    o_rules:
      - regexp: '.*'
  - type: logger
    params: "file:///tmp/ncp/test.log?size=128M&count=8&prefix=SB"
    i_rules:
      - regexp: '.*'


# JSONRPC 2.0 simulation
# ncpio:
#   - type: api
#     i_rules:
#       - regexp: '.*"method".*'
#         invert: true
#     o_rules:
#       - regexp: '.*"method".*'
#   - type: jsonrpc2
#     params: "233"
#     i_rules:
#       - regexp: '.*"method".*'
#     o_rules:
#       - regexp: '.*"method".*'
#         invert: true

log:
  # production: Log output type[xxx] file, development: Log output os.Stdout
  env: "development"
  path: "log/"
  # :debug < :info < :warn < :error < :fatal < :unknown
  # TODO
  # level Not Implement
  level: "info"
  type:
    core: "core"
    tcpc: "client"
    tcps: "server"
    tran: "tran"
    mqtt: "mqtt"
    mqtr: "mqtt_tran"

ncp:
  download:
    map: '../map'
  upload:
    map: '../map'
    air_log: 'log.log'
  status:
    link_id: 2
    position_ok: true
    lat: "22.6876423001"
    lng: "114.2248673001"
    alt: "80.0001"
#  shell:
#    path: "scripts/"
#    prefix: "sh"
#    suffix: ".sh"

