mqttd:
  id: 1
  static:
    link_id: 1
    lat: "22.6876423001"
    lng: "114.2248673001"
    alt: "10088.0001"
  client: "node-%s"
  status:  "nodes/%s/status"
  network: "nodes/%s/network"
  #mqtt: "mqtt[s]://[username][:password]@host.domain[:port]"
  broker: "mqtt://localhost:1883"
  rpc :
    i: "nodes/%s/rpc/recv"
    o: "nodes/%s/rpc/send"
  gtran:
    prefix: "nodes/%s/msg/%s"
  trans:
    wether:
      retain: true
      qos: 0
    battery:
      retain: true
      qos: 0
    sensor:
      retain: true
      qos: 1
    notification:
      retain: true
      qos: 2

# type: tcps / tcpc / mqtt / logger / jsonrpc2 / api
ncpio:
	- type: tcpc
    params: "localhost:8980"
    i_rules:
      - regexp: '.*"method": ?"(webrtc|history|ncp)".*'
        invert: true
      - regexp: '.*"method".*'
    o_rules:
      - regexp: '.*'
  - type: tcps
    params: "localhost:1208"
    i_rules:
      - regexp: '.*"method": ?"webrtc".*'
    o_rules:
      - regexp: '.*"method".*'
        invert: true
      - regexp: '.*'
  - type: mqtt
    params: "/etc/ncp/depot.yml"
    i_rules:
      - regexp: '.*'
    o_rules:
      - regexp: '.*'
  - type: logger
    params: "file:///tmp/ncp/test.log?size=128M&count=8&prefix=SB"
    i_rules:
      - regexp: '.*'

# ncpio:
#   - type: api
#     i_rules:
#       - regexp: '.*'
#         invert: true
#     o_rules:
#       - regexp: '.*'
#         invert: true
#   - type: jsonrpc2
#     params: "233"
#     i_rules:
#       - regexp: '.*'
#         invert: true
#     o_rules:
#       - regexp: '.*'
#         invert: true
#   - type: tcps
#     params: "localhost:1222"
#     i_rules:
#       - regexp: '.*"method".*'
#     o_rules:
#       - regexp: '.*'
#   - type: mqtt
#     params: "config.yml"
#     i_rules:
#       - regexp: '.*'
#     o_rules:
#       - regexp: '.*'
#   - type: logger
#     params: "file:///tmp/ncp/test.log?size=128M&count=8&prefix=SB"
#     i_rules:
#       - regexp: '.*'


# JSONRPC 2.0 simulation
# ncpio:
#   - type: api
#     i_rules:
#       - regexp: '.*"method".*'
#         invert: true
#     o_rules:
#       - regexp: '.*"method".*'
#   - type: jsonrpc2
#     params: "233"
#     i_rules:
#       - regexp: '.*"method".*'
#     o_rules:
#       - regexp: '.*"method".*'
#         invert: true

